-- 코드를 입력하세요
SELECT A.product_code AS PRODUCT_CODE, (A.price * SUM(B.sales_amount)) AS SALES
FROM PRODUCT A JOIN OFFLINE_SALE B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.product_code
ORDER BY SALES DESC, PRODUCT_CODE ASC