-- 코드를 입력하세요
SELECT CAST(DATE_FORMAT(DATETIME, '%H')AS UNSIGNED) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE CAST(DATE_FORMAT(DATETIME, '%H')AS UNSIGNED) BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY HOUR