-- 코드를 작성해주세요
SELECT 
    FISH_INFO.ID,
    FISH_NAME_INFO.FISH_NAME,
    FISH_INFO.LENGTH
FROM 
    FISH_INFO
JOIN 
    FISH_NAME_INFO 
ON 
    FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE 
    FISH_INFO.LENGTH = (
        SELECT 
            MAX(LENGTH) 
        FROM 
            FISH_INFO AS F
        WHERE 
            F.FISH_TYPE = FISH_INFO.FISH_TYPE
    )
ORDER BY 
    FISH_INFO.ID;